pub fn nvrtcGetErrorString (result : nvrtcResult) -> * const :: core :: ffi :: c_char { unsafe { lib () . nvrtcGetErrorString (result : nvrtcResult) } }
pub fn nvrtcVersion (major : * mut :: core :: ffi :: c_int , minor : * mut :: core :: ffi :: c_int ,) -> nvrtcResult { unsafe { lib () . nvrtcVersion (major : * mut :: core :: ffi :: c_int , minor : * mut :: core :: ffi :: c_int ,) } }
pub fn nvrtcGetNumSupportedArchs (numArchs : * mut :: core :: ffi :: c_int) -> nvrtcResult { unsafe { lib () . nvrtcGetNumSupportedArchs (numArchs : * mut :: core :: ffi :: c_int) } }
pub fn nvrtcGetSupportedArchs (supportedArchs : * mut :: core :: ffi :: c_int) -> nvrtcResult { unsafe { lib () . nvrtcGetSupportedArchs (supportedArchs : * mut :: core :: ffi :: c_int) } }
pub fn nvrtcCreateProgram (prog : * mut nvrtcProgram , src : * const :: core :: ffi :: c_char , name : * const :: core :: ffi :: c_char , numHeaders : :: core :: ffi :: c_int , headers : * const * const :: core :: ffi :: c_char , includeNames : * const * const :: core :: ffi :: c_char ,) -> nvrtcResult { unsafe { lib () . nvrtcCreateProgram (prog : * mut nvrtcProgram , src : * const :: core :: ffi :: c_char , name : * const :: core :: ffi :: c_char , numHeaders : :: core :: ffi :: c_int , headers : * const * const :: core :: ffi :: c_char , includeNames : * const * const :: core :: ffi :: c_char ,) } }
pub fn nvrtcDestroyProgram (prog : * mut nvrtcProgram) -> nvrtcResult { unsafe { lib () . nvrtcDestroyProgram (prog : * mut nvrtcProgram) } }
pub fn nvrtcCompileProgram (prog : nvrtcProgram , numOptions : :: core :: ffi :: c_int , options : * const * const :: core :: ffi :: c_char ,) -> nvrtcResult { unsafe { lib () . nvrtcCompileProgram (prog : nvrtcProgram , numOptions : :: core :: ffi :: c_int , options : * const * const :: core :: ffi :: c_char ,) } }
pub fn nvrtcGetPTXSize (prog : nvrtcProgram , ptxSizeRet : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetPTXSize (prog : nvrtcProgram , ptxSizeRet : * mut usize) } }
pub fn nvrtcGetPTX (prog : nvrtcProgram , ptx : * mut :: core :: ffi :: c_char) -> nvrtcResult { unsafe { lib () . nvrtcGetPTX (prog : nvrtcProgram , ptx : * mut :: core :: ffi :: c_char) } }
pub fn nvrtcGetCUBINSize (prog : nvrtcProgram , cubinSizeRet : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetCUBINSize (prog : nvrtcProgram , cubinSizeRet : * mut usize) } }
pub fn nvrtcGetCUBIN (prog : nvrtcProgram , cubin : * mut :: core :: ffi :: c_char) -> nvrtcResult { unsafe { lib () . nvrtcGetCUBIN (prog : nvrtcProgram , cubin : * mut :: core :: ffi :: c_char) } }
pub fn nvrtcGetNVVMSize (prog : nvrtcProgram , nvvmSizeRet : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetNVVMSize (prog : nvrtcProgram , nvvmSizeRet : * mut usize) } }
pub fn nvrtcGetNVVM (prog : nvrtcProgram , nvvm : * mut :: core :: ffi :: c_char) -> nvrtcResult { unsafe { lib () . nvrtcGetNVVM (prog : nvrtcProgram , nvvm : * mut :: core :: ffi :: c_char) } }
pub fn nvrtcGetLTOIRSize (prog : nvrtcProgram , LTOIRSizeRet : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetLTOIRSize (prog : nvrtcProgram , LTOIRSizeRet : * mut usize) } }
pub fn nvrtcGetLTOIR (prog : nvrtcProgram , LTOIR : * mut :: core :: ffi :: c_char) -> nvrtcResult { unsafe { lib () . nvrtcGetLTOIR (prog : nvrtcProgram , LTOIR : * mut :: core :: ffi :: c_char) } }
pub fn nvrtcGetOptiXIRSize (prog : nvrtcProgram , optixirSizeRet : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetOptiXIRSize (prog : nvrtcProgram , optixirSizeRet : * mut usize) } }
pub fn nvrtcGetOptiXIR (prog : nvrtcProgram , optixir : * mut :: core :: ffi :: c_char) -> nvrtcResult { unsafe { lib () . nvrtcGetOptiXIR (prog : nvrtcProgram , optixir : * mut :: core :: ffi :: c_char) } }
pub fn nvrtcGetProgramLogSize (prog : nvrtcProgram , logSizeRet : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetProgramLogSize (prog : nvrtcProgram , logSizeRet : * mut usize) } }
pub fn nvrtcGetProgramLog (prog : nvrtcProgram , log : * mut :: core :: ffi :: c_char) -> nvrtcResult { unsafe { lib () . nvrtcGetProgramLog (prog : nvrtcProgram , log : * mut :: core :: ffi :: c_char) } }
pub fn nvrtcAddNameExpression (prog : nvrtcProgram , name_expression : * const :: core :: ffi :: c_char ,) -> nvrtcResult { unsafe { lib () . nvrtcAddNameExpression (prog : nvrtcProgram , name_expression : * const :: core :: ffi :: c_char ,) } }
pub fn nvrtcGetLoweredName (prog : nvrtcProgram , name_expression : * const :: core :: ffi :: c_char , lowered_name : * mut * const :: core :: ffi :: c_char ,) -> nvrtcResult { unsafe { lib () . nvrtcGetLoweredName (prog : nvrtcProgram , name_expression : * const :: core :: ffi :: c_char , lowered_name : * mut * const :: core :: ffi :: c_char ,) } }
pub fn nvrtcGetPCHHeapSize (ret : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetPCHHeapSize (ret : * mut usize) } }
pub fn nvrtcSetPCHHeapSize (size : usize) -> nvrtcResult { unsafe { lib () . nvrtcSetPCHHeapSize (size : usize) } }
pub fn nvrtcGetPCHCreateStatus (prog : nvrtcProgram) -> nvrtcResult { unsafe { lib () . nvrtcGetPCHCreateStatus (prog : nvrtcProgram) } }
pub fn nvrtcGetPCHHeapSizeRequired (prog : nvrtcProgram , size : * mut usize) -> nvrtcResult { unsafe { lib () . nvrtcGetPCHHeapSizeRequired (prog : nvrtcProgram , size : * mut usize) } }
pub fn nvrtcSetFlowCallback (prog : nvrtcProgram , callback : :: core :: option :: Option < unsafe extern "C" fn (arg1 : * mut :: core :: ffi :: c_void , arg2 : * mut :: core :: ffi :: c_void ,) -> :: core :: ffi :: c_int , > , payload : * mut :: core :: ffi :: c_void ,) -> nvrtcResult { unsafe { lib () . nvrtcSetFlowCallback (prog : nvrtcProgram , callback : :: core :: option :: Option < unsafe extern "C" fn (arg1 : * mut :: core :: ffi :: c_void , arg2 : * mut :: core :: ffi :: c_void ,) -> :: core :: ffi :: c_int , > , payload : * mut :: core :: ffi :: c_void ,) } }
