#!/bin/bash
BASEDIR=$(dirname "$0")
cd "$BASEDIR" || return

echo "Creating artifacts ..."
mkdir artifacts
cd artifacts || return

echo "Generating .ptx file with nvcc ..."
nvcc -keep ../cudnn_kernels.cu > /dev/null 2> /dev/null

echo "Copying cudnn_kernels.ptx ..."
mv cudnn_kernels.ptx ..

cd ..

echo "Reading kernel function names ..."
(sed -n '/^extern \"C\" __global__ void/p' cudnn_kernels.cu | sed -E 's/^extern \"C\" __global__ void ([a-zA-Z0-9_]+).*$/\t\"\1\",/g') | tee >(wc -l > .tmp_lines) > .tmp_data

echo "Creating cudnn_kernel_functions_names.rs ..."
(
    echo -e '/* automatically generated by compile_cudnn_kernels.sh */\npub const FUNCTION_NAMES: [&str; ';
    head -1 .tmp_lines; echo '] = [';
    cat .tmp_data; echo -e '];'
) > cudnn_kernel_functions_names.rs

echo "Removing artifacts/temp files ..."
rm .tmp_data
rm .tmp_lines
rm -rf artifacts

echo "Formatting cudnn_kernel_functions_names.rs ..."
cargo fmt -- cudnn_kernel_functions_names.rs