/* automatically generated by compile_custom_kernels.sh */
pub const FUNCTION_NAMES: [&str; 4] = [
    "division_with_scale_f32",
    "division_f32",
    "division_with_scale_f64",
    "division_f64",
];
