/* automatically generated by compile_custom_kernels.sh */
pub const FUNCTION_NAMES: [&str; 12] = [
    "recip_with_scale_f32",
    "recip_f32",
    "sin_with_scale_f32",
    "sin_f32",
    "cos_with_scale_f32",
    "cos_f32",
    "recip_with_scale_f64",
    "recip_f64",
    "sin_with_scale_f64",
    "sin_f64",
    "cos_with_scale_f64",
    "cos_f64",
];
